baseurl = "heider.design"
title = "Nicolas Heider"
theme = "hugo-creative-portfolio-theme"
languageCode = "de"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet, yellow
  # Use custom.css for your custom styling
  style = "yellow"
  description = "Portfolio of Nicolas Heider"
  copyright = "&copy;2022 Nicolas Heider <br><br>"
  sidebarAbout = [
    "Techn. Produktdesigner (PgK), Student Technisches Design (THI)"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
     #email = "Nicolas.Heider@hallertau.net"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Über mich"
  url = "about/"

  [[params.navlinks]]
  name = "Impressum"
  url = "imprint/"
 

  [params.social]

  #email         = ""
  linkedin      = "https://www.linkedin.com/in/nicolas-heider-087925268/"
  
  
  #youtube       = "full profile url in youtube"
  #twitter       = "full profile url in twitter"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  #github        = "full profile url in github"
  #gitlab        = "full profile url in gitlab"
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #whatsapp      = "wa.me service link"
